// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_extract_graph
int cpp_extract_graph(const std::string& file);
RcppExport SEXP _cppRnet_cpp_extract_graph(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file(fileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extract_graph(file));
    return rcpp_result_gen;
END_RCPP
}
// cpp_extract_data
Rcpp::List cpp_extract_data(const std::string& file, Rcpp::CharacterVector main_sel);
RcppExport SEXP _cppRnet_cpp_extract_data(SEXP fileSEXP, SEXP main_selSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file(fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type main_sel(main_selSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extract_data(file, main_sel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cppRnet_cpp_extract_graph", (DL_FUNC) &_cppRnet_cpp_extract_graph, 1},
    {"_cppRnet_cpp_extract_data", (DL_FUNC) &_cppRnet_cpp_extract_data, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_cppRnet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
