# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_extract_graph <- function(file, out = "") {
    .Call(`_cppRosm_cpp_extract_graph`, file, out)
}

cpp_extract_data <- function(file, main_sel) {
    .Call(`_cppRosm_cpp_extract_data`, file, main_sel)
}

